a = list(range(0,100,10))
a.reverse()
a_dict = dict(enumerate(a))
ret1 = sorted(a_dict)
print(ret1)
ret2 = sorted(a_dict.items(), key=lambda x: x[0])
print(ret2)
ret3 = sorted(a_dict.items(), key=lambda x: x[1])
print(ret3)